os: linux
dist: focal
language: python

python:
  - 3.9

before_deploy:
  - pip install awscli
  - pip install travis-wait-improved
deploy:
 provider: script
 script: travis-wait-improved --timeout 20m aws s3 sync public s3://$BUCKET_NAME --region=$BUCKET_REGION --delete --quiet

install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - cd buildozer
  - python3 setup.py install
  - cd ..

  - sudo apt update
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade Cython virtualenv
  - export PATH=$PATH:~/.local/bin/
  - echo "TODO COMPILE 64bit"
  - yes | buildozer android debug
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/laboratorclient-0.1-arm64-v8a-debug.apk" --tag_name "v.0.1"
  - echo "OK"