# pip freeze | Out-File -Encoding UTF8 requirements.txt

MAX_HISTORY_VALUES = 120
NAMESPACE = "laboratory1"
DEFAULT_ENDPOINT = "opc.tcp://192.168.1.67:4840"
MAX_RECONNECTIONS_NUMBER = 10
RECONNECTION_TIME = 5
GET_FROM_SERVER = 1

KIVY_UPDATE_FUNCTION_TIME = 1
KIVY_DOBLETAP_TIME = 0.3

GRAPH_ADDITIONAL_SPACE_Y = 0.5
GRAPH_BUFFER_AVG_SIZE = 20
GRAPH_ROUND_DIGITS = 1
