# pip freeze | Out-File -Encoding UTF8 requirements.txt

MAX_HISTORY_VALUES = 120
NAMESPACE = "laboratory1"
DEFAULT_ENDPOINT = "opc.tcp://192.168.1.22:4840"
MAX_RECONNECTIONS_NUMBER = 10
RECONNECTION_TIME = 5

KIVY_UPDATE_FUNCTION_TIME = 0.5
KIVY_DOBLETAP_TIME = 0.3
