#:import Factory kivy.factory.Factory

<ListLabVarPopup>:
    title: "Select variable"
    title_align: "center"
    separator_color: 1, 1, 1, 1
    size_hint: None, None
    size: sp(250), sp(500)
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            font_size: sp(30)
            id: list_box
            height: self.minimum_height


<GraphBox>:
    BoxLayout:
        canvas:
            Color:
                rgba: 0.5, 0.5, 0.5, 0.5
            Rectangle:
                pos: self.pos
                size: self.size
            Color:
                rgba: 0, 0, 0, 1
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
        RelativeLayout:
            RelativeLayout:
                canvas:
                    Color:
                        rgba: 0.5, 0.5, 0.5, 0.1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    text: str(root.labvar_value)
                    font_size: sp(50)
                    opacity: 0.1
                BoxLayout:
                    id: plot_box
            RelativeLayout:
                AnchorLayout:
                    anchor_x: "left"
                    anchor_y: "top"
                    padding: sp(10), sp(10), sp(10), sp(10)
                    TouchableLabel:
                        id: btn_close_box
                        size_hint: None, None
                        size: sp(25), sp(25)
                        font_name: "DejaVuSans.ttf"
                        font_size: sp(10)
                        text: "⨯"
                        border_color: 1, 0, 0, 0.4
                        on_release:
                            root.RemoveMe()
                AnchorLayout:
                    id: var_selection_box
                    anchor_x: "right"
                    anchor_y: "top"
                    padding: sp(10), sp(10), sp(10), sp(10)
                    TouchableLabel:
                        id: label_selection
                        size_hint: None, None
                        size: self.size[0], sp(25)
                        font_name: "DejaVuSans.ttf"
                        font_size: sp(10)
                        text: str(root.labvar_name)
                        border_color: 1, 0, 0, 0.4
                        on_release:
                            Factory.ListLabVarPopup().open(root.id)


<GraphContainer>:
    container: graph_container
    scrollview: scroll_view

    ScrollView:
        id: scroll_view
        do_scroll_x: False
        do_scroll_y: True
        GridLayout:
            id: graph_container
            size_hint_y: None
            cols: root.columns
            height: self.minimum_height