#:import ListLabVarPopup libs.listlabvarpopup

<ListLabVarPopup>:
    title: "Select variable"
    title_align: "center"
    separator_color: 1, 1, 1, 1
    size_hint: None, None
    size: sp(250), Window.height - sp(100)
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        bar_width: sp(2)
        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            font_size: sp(30)
            id: list_box
            height: self.minimum_height