#: import TouchableLabel libs.customWidgets

<TouchableLabel>:
    text: root.text
    canvas:
        Color:
            rgba: root.background_color
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: root.border_color
        Line:
            width: 1
            rectangle: self.x, self.y, self.width, self.height
    on_press: root.Pressed()
    on_release: root.Released()